#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-closure-compiler
Version  : 1.1.11
Release  : 6
URL      : https://rubygems.org/downloads/closure-compiler-1.1.11.gem
Source0  : https://rubygems.org/downloads/closure-compiler-1.1.11.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
h1. The Closure Compiler (as a Ruby Gem)
The *closure-compiler* gem is a svelte wrapper around the "Google Closure Compiler":http://code.google.com/closure/compiler/ for JavaScript compression.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n closure-compiler-1.1.11
gem spec %{SOURCE0} -l --ruby > rubygem-closure-compiler.gemspec

%build
gem build rubygem-closure-compiler.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
closure-compiler-1.1.11.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/closure-compiler-1.1.11.gem
/usr/lib64/ruby/gems/2.3.0/gems/closure-compiler-1.1.11/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/closure-compiler-1.1.11/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/closure-compiler-1.1.11/README.textile
/usr/lib64/ruby/gems/2.3.0/gems/closure-compiler-1.1.11/closure-compiler.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/closure-compiler-1.1.11/lib/closure-compiler-20140730.jar
/usr/lib64/ruby/gems/2.3.0/gems/closure-compiler-1.1.11/lib/closure-compiler.rb
/usr/lib64/ruby/gems/2.3.0/gems/closure-compiler-1.1.11/lib/closure/compiler.rb
/usr/lib64/ruby/gems/2.3.0/specifications/closure-compiler-1.1.11.gemspec
